/**
[IDENTITY]: Root Layout
Global Application Shell.

[INPUT]:
- Children(Page Content).

[LINK]:
- GlobalStyles -> ./ globals.css
  - Fonts -> next / font / google
  - Metadata -> Next.js Config

  [OUTPUT]: HTML Document Structure.
[POS]: /frontend/src / app / layout.tsx

[PROTOCOL]:
1. Enforce`lang="en"`(or dynamic locale).
2. Load critical fonts optimization.
3. Apply global CSS overrides.
 */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
