"""add_business_tables

Revision ID: 642a94420db7
Revises: c835b2faaba2
Create Date: 2026-01-02 18:20:29.220050+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '642a94420db7'
down_revision: Union[str, None] = 'c835b2faaba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Enum('ERROR', 'WARNING', 'INFO', name='systemloglevel'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('trace_id', sa.String(length=50), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_logs_component_created', 'system_logs', ['component', 'created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index('ix_system_logs_level_created', 'system_logs', ['level', 'created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_trace_id'), 'system_logs', ['trace_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('preview', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=True, comment='Full path in MinIO: workspaces/{workspace_id}/assets/{asset_id}/{filename}'),
    sa.Column('file_checksum', sa.String(length=64), nullable=True, comment='MD5 checksum for data integrity verification'),
    sa.Column('storage_status', sa.Enum('PENDING_UPLOAD', 'UPLOADING', 'UPLOADED', 'FAILED', 'DELETED', name='storagestatus'), nullable=False, comment='Current storage status in MinIO'),
    sa.Column('uploaded_by', sa.UUID(), nullable=True, comment='User who uploaded the file'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error details if storage_status is FAILED'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_storage_path'), 'assets', ['storage_path'], unique=False)
    op.create_index(op.f('ix_assets_storage_status'), 'assets', ['storage_status'], unique=False)
    op.create_index(op.f('ix_assets_workspace_id'), 'assets', ['workspace_id'], unique=False)
    op.create_table('copy_quotas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('monthly_limit', sa.Integer(), nullable=False),
    sa.Column('used_current_month', sa.Integer(), nullable=False),
    sa.Column('last_reset_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copy_quotas_workspace_id'), 'copy_quotas', ['workspace_id'], unique=True)
    op.create_table('workspace_billing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('credits_remaining', sa.Integer(), nullable=False),
    sa.Column('credits_limit', sa.Integer(), nullable=False),
    sa.Column('reset_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_index('idx_workspace_billing_active_tier', 'workspace_billing', ['is_active', 'tier'], unique=False)
    op.create_index('idx_workspace_billing_reset', 'workspace_billing', ['reset_date'], unique=False)
    op.create_index('idx_workspace_billing_workspace', 'workspace_billing', ['workspace_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('CLOTHING', 'ELECTRONICS', 'BEAUTY', 'HOME', 'FOOD', 'SPORTS', 'TOYS', 'BOOKS', 'AUTOMOTIVE', 'HEALTH', 'OTHER', name='productcategory'), nullable=False),
    sa.Column('selling_points', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('target_audience', sa.String(length=500), nullable=True),
    sa.Column('original_asset_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'PROCESSING', 'COMPLETED', 'ARCHIVED', name='productstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['original_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_workspace_id'), 'products', ['workspace_id'], unique=False)
    op.create_table('copy_generation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('copy_type', sa.Enum('TITLES', 'SELLING_POINTS', 'FAQ', 'DESCRIPTIONS', name='copytype'), nullable=False),
    sa.Column('tone', sa.Enum('PROFESSIONAL', 'CASUAL', 'PLAYFUL', 'LUXURY', name='tone'), nullable=False),
    sa.Column('audience', sa.Enum('B2B', 'B2C', 'TECHNICAL', name='audience'), nullable=False),
    sa.Column('length', sa.Enum('SHORT', 'MEDIUM', 'LONG', name='length'), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copy_generation_jobs_task_id'), 'copy_generation_jobs', ['task_id'], unique=True)
    op.create_index(op.f('ix_copy_generation_jobs_workspace_id'), 'copy_generation_jobs', ['workspace_id'], unique=False)
    op.create_table('image_generation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('reference_image_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('style_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_urls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_image_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_generation_jobs_reference_image_id'), 'image_generation_jobs', ['reference_image_id'], unique=False)
    op.create_index(op.f('ix_image_generation_jobs_task_id'), 'image_generation_jobs', ['task_id'], unique=True)
    op.create_index(op.f('ix_image_generation_jobs_workspace_id'), 'image_generation_jobs', ['workspace_id'], unique=False)
    op.create_table('video_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('CREATIVE_AD', 'FUNCTIONAL_INTRO', name='videomode'), nullable=False),
    sa.Column('target_duration', sa.Integer(), nullable=False),
    sa.Column('script', sa.JSON(), nullable=True),
    sa.Column('storyboard', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SCRIPT_READY', 'COMPLETED', 'FAILED', name='videoprojectstatus'), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_projects_product_id'), 'video_projects', ['product_id'], unique=False)
    op.create_index(op.f('ix_video_projects_status'), 'video_projects', ['status'], unique=False)
    op.create_index(op.f('ix_video_projects_user_id'), 'video_projects', ['user_id'], unique=False)
    op.create_index(op.f('ix_video_projects_workspace_id'), 'video_projects', ['workspace_id'], unique=False)
    op.create_table('copy_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('generation_job_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('copy_type', sa.Enum('TITLES', 'SELLING_POINTS', 'FAQ', 'DESCRIPTIONS', name='copytype'), nullable=False),
    sa.Column('generation_config', sa.JSON(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_job_id'], ['copy_generation_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copy_results_generation_job_id'), 'copy_results', ['generation_job_id'], unique=False)
    op.create_index(op.f('ix_copy_results_product_id'), 'copy_results', ['product_id'], unique=False)
    op.create_index(op.f('ix_copy_results_workspace_id'), 'copy_results', ['workspace_id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('generation_job_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_url', sa.String(length=1024), nullable=True),
    sa.Column('processed_url', sa.String(length=1024), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('image_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_job_id'], ['image_generation_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_generation_job_id'), 'images', ['generation_job_id'], unique=False)
    op.create_index(op.f('ix_images_workspace_id'), 'images', ['workspace_id'], unique=False)
    op.create_table('video_generation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('video_project_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generation_config', sa.JSON(), nullable=False),
    sa.Column('raw_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_project_id'], ['video_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_generation_jobs_status'), 'video_generation_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_video_generation_jobs_task_id'), 'video_generation_jobs', ['task_id'], unique=True)
    op.create_index(op.f('ix_video_generation_jobs_user_id'), 'video_generation_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_video_generation_jobs_video_project_id'), 'video_generation_jobs', ['video_project_id'], unique=False)
    op.create_index(op.f('ix_video_generation_jobs_workspace_id'), 'video_generation_jobs', ['workspace_id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='videostatus'), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('quality', sa.Enum('HD_720', 'HD_1080', 'UHD_4K', name='videoquality'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['video_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_project_id'), 'videos', ['project_id'], unique=False)
    op.create_index(op.f('ix_videos_status'), 'videos', ['status'], unique=False)
    op.create_index(op.f('ix_videos_task_id'), 'videos', ['task_id'], unique=False)
    op.create_index(op.f('ix_videos_user_id'), 'videos', ['user_id'], unique=False)
    op.create_index(op.f('ix_videos_workspace_id'), 'videos', ['workspace_id'], unique=False)
    op.create_table('video_audio_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('voice_id', sa.String(length=100), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_audio_tracks_video_id'), 'video_audio_tracks', ['video_id'], unique=False)
    op.create_index(op.f('ix_video_audio_tracks_workspace_id'), 'video_audio_tracks', ['workspace_id'], unique=False)
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_users_is_superuser'), 'users', ['is_superuser'], unique=False)
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('workspaces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('workspaces', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_is_superuser'), table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('users', 'is_superuser')
    op.drop_index(op.f('ix_video_audio_tracks_workspace_id'), table_name='video_audio_tracks')
    op.drop_index(op.f('ix_video_audio_tracks_video_id'), table_name='video_audio_tracks')
    op.drop_table('video_audio_tracks')
    op.drop_index(op.f('ix_videos_workspace_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_user_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_task_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_project_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_video_generation_jobs_workspace_id'), table_name='video_generation_jobs')
    op.drop_index(op.f('ix_video_generation_jobs_video_project_id'), table_name='video_generation_jobs')
    op.drop_index(op.f('ix_video_generation_jobs_user_id'), table_name='video_generation_jobs')
    op.drop_index(op.f('ix_video_generation_jobs_task_id'), table_name='video_generation_jobs')
    op.drop_index(op.f('ix_video_generation_jobs_status'), table_name='video_generation_jobs')
    op.drop_table('video_generation_jobs')
    op.drop_index(op.f('ix_images_workspace_id'), table_name='images')
    op.drop_index(op.f('ix_images_generation_job_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_copy_results_workspace_id'), table_name='copy_results')
    op.drop_index(op.f('ix_copy_results_product_id'), table_name='copy_results')
    op.drop_index(op.f('ix_copy_results_generation_job_id'), table_name='copy_results')
    op.drop_table('copy_results')
    op.drop_index(op.f('ix_video_projects_workspace_id'), table_name='video_projects')
    op.drop_index(op.f('ix_video_projects_user_id'), table_name='video_projects')
    op.drop_index(op.f('ix_video_projects_status'), table_name='video_projects')
    op.drop_index(op.f('ix_video_projects_product_id'), table_name='video_projects')
    op.drop_table('video_projects')
    op.drop_index(op.f('ix_image_generation_jobs_workspace_id'), table_name='image_generation_jobs')
    op.drop_index(op.f('ix_image_generation_jobs_task_id'), table_name='image_generation_jobs')
    op.drop_index(op.f('ix_image_generation_jobs_reference_image_id'), table_name='image_generation_jobs')
    op.drop_table('image_generation_jobs')
    op.drop_index(op.f('ix_copy_generation_jobs_workspace_id'), table_name='copy_generation_jobs')
    op.drop_index(op.f('ix_copy_generation_jobs_task_id'), table_name='copy_generation_jobs')
    op.drop_table('copy_generation_jobs')
    op.drop_index(op.f('ix_products_workspace_id'), table_name='products')
    op.drop_table('products')
    op.drop_index('idx_workspace_billing_workspace', table_name='workspace_billing')
    op.drop_index('idx_workspace_billing_reset', table_name='workspace_billing')
    op.drop_index('idx_workspace_billing_active_tier', table_name='workspace_billing')
    op.drop_table('workspace_billing')
    op.drop_index(op.f('ix_copy_quotas_workspace_id'), table_name='copy_quotas')
    op.drop_table('copy_quotas')
    op.drop_index(op.f('ix_assets_workspace_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_storage_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_storage_path'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_system_logs_trace_id'), table_name='system_logs')
    op.drop_index('ix_system_logs_level_created', table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_index('ix_system_logs_component_created', table_name='system_logs')
    op.drop_table('system_logs')
    # ### end Alembic commands ###
